name: ibi
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.8
    - jupyterlab>=3
    - ipywidgets
    - numpy
    - scipy
    - pandas
    - xlrd
    - matplotlib
    - biopython
    - nodejs

